/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package eu.scasefp7.eclipse.umlrec.internal;
import java.util.ArrayList;

import eu.scasefp7.eclipse.umlrec.MissingRecognizerNativeException;

public class UMLRecognizerJNI {

    static {
    	// Ignore compiler warnings about not completing the initializer
    	if(true) {
    		throw new MissingRecognizerNativeException("Fragment with native libraries not loaded");
    	}
    }

    public final static native long new_StringList__SWIG_0();
    public final static native long new_StringList__SWIG_1(long jarg1);
    public final static native long new_StringList__SWIG_2(long jarg1, StringList jarg1_);
	public final static native long StringList_capacity(long jarg1, StringList jarg1_);
	public final static native void StringList_reserve(long jarg1, StringList jarg1_, long jarg2);
	public final static native boolean StringList_isEmpty(long jarg1, StringList jarg1_);
	public final static native void StringList_clear(long jarg1, StringList jarg1_);
	public final static native void StringList_push_back(long jarg1, StringList jarg1_, String jarg2);
	public final static native String StringList_get(long jarg1, StringList jarg1_, int jarg2);
	public final static native String StringList_set(long jarg1, StringList jarg1_, int jarg2, String jarg3);
	public final static native int StringList_size(long jarg1, StringList jarg1_);
	public final static native void StringList_removeRange(long jarg1, StringList jarg1_, int jarg2, int jarg3);
	public final static native void delete_StringList(long jarg1);
	public final static native long new_UMLrecog();
	public final static native void delete_UMLrecog(long jarg1);
	public final static native void UMLrecog_clear(long jarg1, UMLrecog jarg1_);
	public final static native void UMLrecog_setParameters__SWIG_0(long jarg1, UMLrecog jarg1_, boolean jarg2, boolean jarg3, int jarg4, double jarg5, double jarg6, double jarg7);
	public final static native void UMLrecog_setParameters__SWIG_1(long jarg1, UMLrecog jarg1_, boolean jarg2, boolean jarg3, int jarg4, double jarg5, double jarg6);
	public final static native void UMLrecog_setParameters__SWIG_2(long jarg1, UMLrecog jarg1_, boolean jarg2, boolean jarg3, int jarg4, double jarg5);
	public final static native void UMLrecog_setParameters__SWIG_3(long jarg1, UMLrecog jarg1_, boolean jarg2, boolean jarg3, int jarg4);
	public final static native void UMLrecog_setParameters__SWIG_4(long jarg1, UMLrecog jarg1_, boolean jarg2, boolean jarg3);
	public final static native void UMLrecog_setParameters__SWIG_5(long jarg1, UMLrecog jarg1_, boolean jarg2);
	public final static native void UMLrecog_setParameters__SWIG_6(long jarg1, UMLrecog jarg1_);
	public final static native boolean UMLrecog_setImage(long jarg1, UMLrecog jarg1_, String jarg2);
	public final static native void UMLrecog_setTessPath(long jarg1, UMLrecog jarg1_, String jarg2);
	public final static native int UMLrecog_process(long jarg1, UMLrecog jarg1_);
	public final static native long UMLrecog_getXMIcontent(long jarg1, UMLrecog jarg1_);
}
